---
- name: task1_3
  hosts: web
  user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: net.ifnames exist
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*net.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'
  - name: biosdevname exist
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
  - name: Run command grub2-mkconfig
    ansible.builtin.shell:
      cmd: /bin/bash grub2-mkconfig
